### ISSUE TITLE
Migrating from another php ERP to Moqui platform?

### ISSUE THREAD

**Issue by topstarnetwork** [jonesde/OFBizMigrate#1]
Hello, I am running a hosting billing software in php/mysql here https://hostbillapp.com/
and I was wondering if it would be possible to migrate all this hostbill applications to moqui platform.
Instead of having to write the code again?
regards, Heather

**Comment by jonesde** [comment]
PHP is a very different language from Java, and Moqui Framework is one of many toolsets for building enterprise applications in Java each having different APIs so code is different from one to the next. Changing to a different tool set is never something that can be done automatically, always requires human effort.
