### ISSUE TITLE
Can we port any kind of java jsp website to moqui framework?

### ISSUE THREAD

**Issue by topstarnetwork** [jonesde/OFBizMigrate#2]
Hello, Can we port any kind of java jsp website to moqui framework?
For exemple the way you did for apache ofbiz, could we do this for exemple with java standard softwares?
If so what is the tutoral?
Regards, Heather

**Comment by jonesde** [comment]
This repository has simple FreeMarker templates with macros to transform XML files from one structure (OFBiz XML files) to another (Moqui XML files). Moqui is a tool set, not a template language like JSP or a programming language like Java, so there is nothing with a well defined and simple structure to transform.

If you want to open a discussion with a more detailed explanation of what you are trying to do please do so in the Moqui Ecosystem group on LinkedIn where others can see and comment.

**Comment by topstarnetwork** [comment]
Ok, I will open a ticket on linkedin when I'll be ready with my project,
In any case is the apache ofbiz that you ported to moqui ready for production?
If I use moqui ofbiz port do we see any change from the outside or does ofbiz looks like the original one?
thanks.

**Comment by jonesde** [comment]
These simple Apache OFBiz entity and service definition migration tools were a small project I worked on and haven't updated for about 5 years now. There is no comprehensive migration of OFBiz artifacts to run on Moqui. That sort of effort has been discussed on the OFBiz mailing lists various times in the context of a change for OFBiz to use Moqui Framework, but doing so would be a massive effort and without a large community around it of very little use.

Moqui Framework is a complete redesign and rewrite based on some of the concepts in Apache OFBiz and going far beyond what is in the OFBiz framework. As part of this effort the business level artifacts like entities (the data model), services, and screens have also been redesigned and rewritten. In other words, part of the whole point is that there is a lot of room for improvement in the OFBiz entities, services, and screens so it never made sense to port them.

If you already have custom code and applications built with OFBiz and would like to move to Moqui it would require some development effort to do so. If you are just getting started it is easiest to use the latest code from the various Moqui Ecosystem repositories and build from there.
